name: Linux
on:
  push:
    branches: [avalonia]
  pull_request:
    branches: [avalonia]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
            
    - name: Build
      run: dotnet build -c Linux

    - name: Upload Plugin Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ClassicAssist.Avalonia-${{ matrix.os }}
        path: ./Output/net48
